package main

import (
	"strings"
	"testing"
	"time"

	gitlab "gitlab.com/gitlab-org/api/client-go/v2"
)

func mkNote(body, author string, id int64, createdAt string) note {
	var n note
	n.ID = id
	n.Body = body
	n.Author.Username = author
	n.CreatedAt = createdAt
	return n
}

const botBody = "Diffs:\n- https://github.com/org/app/compare/v1...v2\n- https://gitlab.cee.redhat.com/g/p/-/compare/a...b\nnot a url line"

func TestParseMRArg(t *testing.T) {
	cases := []struct {
		name     string
		arg      string
		wantHost string
		wantIID  int64
		wantErr  bool
	}{
		{"bare iid", "12345", "h.example.com", 12345, false},
		{"full url", "https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/98765", "gitlab.cee.redhat.com", 98765, false},
		{"wrong project", "https://gitlab.cee.redhat.com/other/repo/-/merge_requests/1", "", 0, true},
		{"not a number", "not-a-number", "", 0, true},
		{"negative", "-3", "", 0, true},
	}
	for _, c := range cases {
		host, iid, err := parseMRArg(c.arg, "h.example.com")
		if (err != nil) != c.wantErr {
			t.Errorf("%s: err=%v, wantErr=%v", c.name, err, c.wantErr)
			continue
		}
		if err == nil && (host != c.wantHost || iid != c.wantIID) {
			t.Errorf("%s: got (%q, %d), want (%q, %d)", c.name, host, iid, c.wantHost, c.wantIID)
		}
	}
}

func TestExtractDiffURLsNewestBotCommentWins(t *testing.T) {
	notes := []note{ // newest first, as the API returns them
		mkNote("Diffs:\n- https://github.com/org/app/compare/v2...v3", botUsername, 9, "2026-08-27T11:00:00Z"),
		mkNote(botBody, botUsername, 1, "2026-08-27T10:00:00Z"),
	}
	urls, err := extractDiffURLs(notes)
	if err != nil {
		t.Fatal(err)
	}
	if len(urls) != 1 || urls[0] != "https://github.com/org/app/compare/v2...v3" {
		t.Fatalf("got %v", urls)
	}
}

func TestExtractDiffURLsIgnoresNonBotAndNonDiffs(t *testing.T) {
	notes := []note{
		mkNote("Diffs:\n- https://github.com/evil/evil/compare/a...b", "attacker", 3, "2026-08-27T10:00:00Z"),
		mkNote("looks normal", botUsername, 2, "2026-08-27T10:00:00Z"),
		mkNote(botBody, botUsername, 1, "2026-08-27T10:00:00Z"),
	}
	urls, err := extractDiffURLs(notes)
	if err != nil {
		t.Fatal(err)
	}
	if len(urls) != 2 {
		t.Fatalf("expected the 2 URLs from the real bot comment, got %v", urls)
	}
}

func TestExtractDiffURLsNoBotComment(t *testing.T) {
	if _, err := extractDiffURLs([]note{mkNote("hello", "someone", 1, "2026-08-27T10:00:00Z")}); err == nil {
		t.Fatal("expected an error when no devtools-bot Diffs comment exists")
	}
}

func TestExtractGuidance(t *testing.T) {
	notes := []note{ // newest first
		mkNote("/soundings note newer guidance", "alice", 3, "2026-08-27T11:00:00Z"),
		mkNote("/SOUNDINGS NOTE older\nspanning lines", "bob", 2, "2026-08-27T10:00:00Z"),
		mkNote("just a comment", "carol", 1, "2026-08-27T09:00:00Z"),
	}
	g := extractGuidance(notes, "https://h/mr/1")
	if len(g) != 2 {
		t.Fatalf("got %d entries", len(g))
	}
	if g[0].Author != "bob" || g[0].Content != "older\nspanning lines" {
		t.Errorf("oldest first expected, got %+v", g[0])
	}
	if g[1].CommentURL != "https://h/mr/1#note_3" {
		t.Errorf("got comment url %q", g[1].CommentURL)
	}
}

func TestExtractGuidanceIgnoresLegacyRCSNote(t *testing.T) {
	if g := extractGuidance([]note{mkNote("/rcs note old convention", "bob", 1, "2026-08-27T10:00:00Z")}, "u"); len(g) != 0 {
		t.Fatalf("legacy /rcs note must be ignored, got %+v", g)
	}
}

func TestExtractGuidanceSkipsMissingCreatedAt(t *testing.T) {
	if g := extractGuidance([]note{mkNote("/soundings note x", "bob", 1, "")}, "u"); len(g) != 0 {
		t.Fatalf("expected no entries, got %+v", g)
	}
}

func TestAnnotateReportInsertsBannerWhenNotRecommended(t *testing.T) {
	report := "**Recommendation:** 🚫 **RELEASE NOT RECOMMENDED**\n\nSummary text.\n\n---\n\n## Risk Analysis\n"
	got := annotateReport(report, "")
	if !strings.Contains(got, overrideBanner) {
		t.Fatalf("expected banner to be inserted, got %q", got)
	}
	if bannerIdx, sepIdx := strings.Index(got, overrideBanner), strings.Index(got, "---"); bannerIdx >= sepIdx {
		t.Fatalf("expected banner before the separator, got %q", got)
	}
	// A paragraph immediately followed by "---" on the next line is parsed
	// as a Setext H2 heading in CommonMark, not a thematic break - the
	// banner and the separator must be split by a blank line or the
	// separator silently stops rendering as a horizontal rule.
	if !strings.Contains(got, "tool.\n\n---") {
		t.Fatalf("expected a blank line between the banner and the separator, got %q", got)
	}
}

func TestAnnotateReportLeavesOtherRecommendationsUnchanged(t *testing.T) {
	report := "**Recommendation:** ⚠️ **MANUAL REVIEW REQUIRED**\n\nSummary text.\n\n---\n\n## Risk Analysis\n"
	if got := annotateReport(report, ""); got != report {
		t.Fatalf("expected no change, got %q", got)
	}
}

func TestAnnotateReportIsIdempotent(t *testing.T) {
	report := "**Recommendation:** 🚫 **RELEASE NOT RECOMMENDED**\n\nSummary text.\n\n---\n\n## Risk Analysis\n\n---\n\n*🤖 Generated by [Soundings](https://x) | model | now*"
	once := annotateReport(report, "https://forms.gle/feedback")
	twice := annotateReport(once, "https://forms.gle/feedback")
	if once != twice {
		t.Fatalf("expected a second pass to be a no-op, got %q", twice)
	}
}

func TestAnnotateReportNoSeparatorLeavesUnchanged(t *testing.T) {
	report := "**Recommendation:** 🚫 **RELEASE NOT RECOMMENDED**\n\nSummary text with no separator line.\n"
	if got := annotateReport(report, ""); got != report {
		t.Fatalf("expected no change without a separator line, got %q", got)
	}
}

func TestAnnotateReportInsertsFeedbackLinkBeforeAttribution(t *testing.T) {
	report := "Summary.\n\n---\n\n*🤖 Generated by [Soundings](https://github.com/gwenneg/soundings) | model | now*"
	got := annotateReport(report, "https://forms.gle/feedback")
	if !strings.Contains(got, "https://forms.gle/feedback") {
		t.Fatalf("expected feedback URL to be inserted, got %q", got)
	}
	if linkIdx, attrIdx := strings.Index(got, "Share your feedback"), strings.Index(got, "Generated by"); linkIdx >= attrIdx {
		t.Fatalf("expected feedback link before the attribution line, got %q", got)
	}
}

func TestAnnotateReportNoFeedbackURLLeavesUnchanged(t *testing.T) {
	report := "Summary.\n\n---\n\n*🤖 Generated by [Soundings](https://github.com/gwenneg/soundings) | model | now*"
	if got := annotateReport(report, ""); got != report {
		t.Fatalf("expected no change without a feedback URL, got %q", got)
	}
}

func TestAnnotateReportBannerAndFeedbackCombine(t *testing.T) {
	report := "**Recommendation:** 🚫 **RELEASE NOT RECOMMENDED**\n\nSummary text.\n\n---\n\n## Risk Analysis\n\n---\n\n*🤖 Generated by [Soundings](https://github.com/gwenneg/soundings) | model | now*"
	got := annotateReport(report, "https://forms.gle/feedback")
	if !strings.Contains(got, overrideBanner) {
		t.Fatalf("expected banner to be inserted, got %q", got)
	}
	if !strings.Contains(got, "https://forms.gle/feedback") {
		t.Fatalf("expected feedback URL to be inserted, got %q", got)
	}
}

func TestFromSDK(t *testing.T) {
	created := time.Date(2026, 8, 27, 10, 0, 0, 0, time.UTC)
	sdkNote := &gitlab.Note{ID: 7, Body: "hello", CreatedAt: &created}
	sdkNote.Author.Username = "alice"
	n := fromSDK(sdkNote)
	if n.ID != 7 || n.Body != "hello" || n.Author.Username != "alice" || n.CreatedAt != "2026-08-27T10:00:00Z" {
		t.Fatalf("got %+v", n)
	}
	if n := fromSDK(&gitlab.Note{ID: 8}); n.CreatedAt != "" {
		t.Fatalf("nil CreatedAt must map to empty string, got %q", n.CreatedAt)
	}
}

func TestEnvThreshold(t *testing.T) {
	t.Setenv("X_THRESHOLD", "0")
	n, err := envThreshold("X_THRESHOLD")
	if err != nil || n == nil || *n != 0 {
		t.Fatalf("explicit 0 must survive, got %v, %v", n, err)
	}
	t.Setenv("X_THRESHOLD", "101")
	if _, err := envThreshold("X_THRESHOLD"); err == nil {
		t.Fatal("out-of-range threshold must fail")
	}
}

func TestValidateThresholdOrder(t *testing.T) {
	ptr := func(n int) *int { return &n }

	if err := validateThresholdOrder(nil, nil); err != nil {
		t.Errorf("both unset must not error, got %v", err)
	}
	if err := validateThresholdOrder(ptr(80), nil); err != nil {
		t.Errorf("one unset must not error, got %v", err)
	}
	if err := validateThresholdOrder(ptr(80), ptr(60)); err != nil {
		t.Errorf("auto-deploy >= review-required must not error, got %v", err)
	}
	if err := validateThresholdOrder(ptr(80), ptr(80)); err != nil {
		t.Errorf("equal thresholds must not error, got %v", err)
	}
	if err := validateThresholdOrder(ptr(60), ptr(80)); err == nil {
		t.Fatal("swapped thresholds (auto-deploy < review-required) must error")
	}
}

func TestPluginVersionFromManifest(t *testing.T) {
	if pluginVersion == "unknown" || pluginVersion == "" {
		t.Fatalf("pluginVersion = %q: the embedded .claude-plugin/plugin.json did not yield a version", pluginVersion)
	}
}
