// Command soundings-app-interface is the deterministic helper behind the
// soundings-app-interface Claude Code plugin. With no arguments it runs as
// an MCP server over stdio exposing the resolve, annotate, and post tools
// (see mcp.go); the same operations are also available as subcommands for
// local use:
//
//	resolve <MR IID or URL>          Resolve an app-interface MR into
//	                                 soundings inputs: the compare URLs from
//	                                 the newest devtools-bot "Diffs:"
//	                                 comment, the MR's "/soundings note"
//	                                 guidance comments (pre-authorized - the
//	                                 MR itself is permission-gated), and any
//	                                 configured thresholds/feedback URL.
//	                                 Prints one JSON object.
//
//	annotate <file> [feedback URL]   Insert app-interface's own
//	                                 override-justification banner into a
//	                                 rendered soundings report, in place,
//	                                 when its recommendation is "RELEASE
//	                                 NOT RECOMMENDED", and the compliance-
//	                                 mandated feedback link when a feedback
//	                                 URL is given. Both are no-ops when
//	                                 their condition doesn't apply, and
//	                                 idempotent if run twice.
//
//	post <MR IID or URL> <file>      Post a report markdown file to the MR
//	                                 as a NEW comment - never an edit - so
//	                                 re-runs keep an audit trail. Prints the
//	                                 posted comment's URL.
//
//	hook                             Run as a Claude Code PreToolUse hook:
//	                                 pre-approve this plugin's own MCP
//	                                 tools (resolve, annotate, post). See
//	                                 hook.go.
//
// GitLab access uses the official Go SDK, authenticated by GITLAB_TOKEN -
// the user's own personal access token, so everything happens under their
// identity. TLS is always verified against the operating system's
// certificate store, which is where a corporate CA lives; there is
// deliberately no skip option. The helper only ever reads or writes MR
// notes - fetching diff content stays inside soundings.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"os"
	"regexp"
	"strconv"
	"strings"
	"time"

	gitlab "gitlab.com/gitlab-org/api/client-go/v2"
)

// pluginVersion mirrors .claude-plugin/plugin.json; bump both together.
const pluginVersion = "0.5.0"

const (
	project     = "service/app-interface"
	botUsername = "devtools-bot"
	diffsMarker = "Diffs:"
	defaultHost = "gitlab.cee.redhat.com"

	notRecommendedMarker = "RELEASE NOT RECOMMENDED"
	overrideBanner       = "\n**🔓 Override Justification Required** — If you proceed with this release despite this recommendation, post a comment in this merge request using `/soundings override <your justification>`. This creates an audit trail and helps improve the tool.\n\n"

	feedbackLineFormat = "💬 **[Share your feedback on this report](%s)** — Were the risks accurate? Were the action items useful? Your feedback helps improve Soundings.\n\n"
)

var (
	// URLs on lines starting with "- " inside the bot comment.
	urlRe = regexp.MustCompile(`(?m)^- (https?://\S+)$`)
	// "/soundings note <text>", multiline and case-insensitive.
	guidanceRe = regexp.MustCompile(`(?is)^\s*/soundings\s+note\s+(\S.*\S|\S)`)
	mrURLRe    = regexp.MustCompile(`^https?://([^/]+)/(.+)/-/merge_requests/(\d+)`)
	// The horizontal-rule line the soundings report template emits right
	// after the summary paragraph - where the banner is inserted.
	separatorLineRe = regexp.MustCompile(`(?m)^---\s*$`)
	// The report's closing attribution line - the feedback link goes
	// right before it.
	generatedByLineRe = regexp.MustCompile(`(?m)^\*🤖 Generated by`)
)

func main() {
	initLogging()

	var err error
	switch {
	case len(os.Args) == 1:
		err = runMCP()
		// stdin closing is the normal way a stdio MCP session ends
		if err != nil && strings.Contains(err.Error(), "EOF") {
			err = nil
		}
	case len(os.Args) == 3 && os.Args[1] == "resolve":
		err = runResolve(os.Args[2])
	case len(os.Args) == 3 && os.Args[1] == "annotate":
		err = runAnnotate(os.Args[2], "")
	case len(os.Args) == 4 && os.Args[1] == "annotate":
		err = runAnnotate(os.Args[2], os.Args[3])
	case len(os.Args) == 4 && os.Args[1] == "post":
		err = runPost(os.Args[2], os.Args[3])
	case len(os.Args) == 2 && os.Args[1] == "hook":
		err = runHook(os.Stdin, os.Stdout)
	default:
		err = errors.New("usage: no arguments (stdio MCP server) | resolve <MR IID or URL> | annotate <report markdown file> [feedback URL] | post <MR IID or URL> <report markdown file> | hook (as a PreToolUse hook)")
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "soundings-app-interface: %v\n", err)
		os.Exit(1)
	}
}

func initLogging() {
	level := slog.LevelInfo
	if v := os.Getenv("SOUNDINGS_LOG_LEVEL"); v != "" {
		switch strings.ToLower(v) {
		case "debug":
			level = slog.LevelDebug
		case "info":
			level = slog.LevelInfo
		case "warn":
			level = slog.LevelWarn
		case "error":
			level = slog.LevelError
		default:
			fmt.Fprintf(os.Stderr, "soundings-app-interface: SOUNDINGS_LOG_LEVEL=%q is not recognized (valid: debug, info, warn, error); using info\n", v)
		}
	}
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: level})))
}

// note is the subset of a GitLab MR note the helper works with; keeping it
// as an internal type keeps the extraction logic and its tests SDK-free.
type note struct {
	ID     int64 `json:"id"`
	Author struct {
		Username string `json:"username"`
	} `json:"author"`
	Body      string `json:"body"`
	CreatedAt string `json:"created_at"`
}

type guidanceEntry struct {
	Content    string `json:"content"`
	Author     string `json:"author"`
	Date       string `json:"date"`
	CommentURL string `json:"comment_url"`
}

type resolveOutput struct {
	MRURL          string          `json:"mr_url"`
	DiffURLs       []string        `json:"diff_urls"`
	Guidance       []guidanceEntry `json:"guidance"`
	FeedbackURL    string          `json:"feedback_url,omitempty"`
	AutoDeploy     *int            `json:"auto_deploy,omitempty"`
	ReviewRequired *int            `json:"review_required,omitempty"`
}

func runResolve(mrArg string) error {
	out, err := doResolve(mrArg)
	if err != nil {
		return err
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(out)
}

// doResolve is the core of the resolve operation, shared by the CLI and
// the MCP server.
func doResolve(mrArg string) (*resolveOutput, error) {
	host, iid, err := parseMRArg(mrArg, envHost())
	if err != nil {
		return nil, err
	}
	mrURL := fmt.Sprintf("https://%s/%s/-/merge_requests/%d", host, project, iid)
	slog.Info("Resolving app-interface MR", "mr_iid", iid, "host", host)

	client, err := newGitLabClient(host)
	if err != nil {
		return nil, err
	}
	notes, err := fetchNotes(client, host, iid)
	if err != nil {
		return nil, err
	}
	diffURLs, err := extractDiffURLs(notes)
	if err != nil {
		return nil, err
	}
	guidance := extractGuidance(notes, mrURL)
	out := &resolveOutput{MRURL: mrURL, DiffURLs: diffURLs, Guidance: guidance}
	out.FeedbackURL = os.Getenv("SOUNDINGS_FEEDBACK_URL")
	if out.AutoDeploy, err = envThreshold("SOUNDINGS_AUTO_DEPLOY_THRESHOLD"); err != nil {
		return nil, err
	}
	if out.ReviewRequired, err = envThreshold("SOUNDINGS_REVIEW_REQUIRED_THRESHOLD"); err != nil {
		return nil, err
	}
	if err := validateThresholdOrder(out.AutoDeploy, out.ReviewRequired); err != nil {
		return nil, err
	}
	return out, nil
}

// runAnnotate inserts app-interface's own report additions - the
// override-justification banner and the compliance-mandated feedback
// link - into a rendered soundings report, in place. Soundings itself has
// no notion of either convention; both are entirely app-interface's own.
func runAnnotate(reportPath, feedbackURL string) error {
	_, err := doAnnotate(reportPath, feedbackURL)
	return err
}

// doAnnotate is the core of the annotate operation, shared by the CLI and
// the MCP server. It reports whether the file was modified.
func doAnnotate(reportPath, feedbackURL string) (bool, error) {
	body, err := os.ReadFile(reportPath)
	if err != nil {
		return false, fmt.Errorf("cannot read report file: %w", err)
	}
	annotated := annotateReport(string(body), feedbackURL)
	if annotated == string(body) {
		return false, nil
	}
	if err := os.WriteFile(reportPath, []byte(annotated), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// annotateReport is the pure text transform behind runAnnotate. It is
// idempotent: a report that already carries the banner or the feedback
// link, or for which the corresponding condition doesn't apply, is
// returned unchanged on that part.
func annotateReport(markdown, feedbackURL string) string {
	markdown = insertOverrideBanner(markdown)
	markdown = insertFeedbackLink(markdown, feedbackURL)
	return markdown
}

// insertOverrideBanner adds the audit-trail banner right after the summary
// paragraph when the recommendation is "RELEASE NOT RECOMMENDED".
func insertOverrideBanner(markdown string) string {
	if !strings.Contains(markdown, notRecommendedMarker) || strings.Contains(markdown, overrideBanner) {
		return markdown
	}
	loc := separatorLineRe.FindStringIndex(markdown)
	if loc == nil {
		return markdown
	}
	return markdown[:loc[0]] + overrideBanner + markdown[loc[0]:]
}

// insertFeedbackLink adds the compliance-mandated feedback link right
// before the report's closing attribution line, when a feedback URL is
// configured.
func insertFeedbackLink(markdown, feedbackURL string) string {
	if feedbackURL == "" || strings.Contains(markdown, feedbackURL) {
		return markdown
	}
	loc := generatedByLineRe.FindStringIndex(markdown)
	if loc == nil {
		return markdown
	}
	line := fmt.Sprintf(feedbackLineFormat, feedbackURL)
	return markdown[:loc[0]] + line + markdown[loc[0]:]
}

func runPost(mrArg, reportPath string) error {
	url, err := doPost(mrArg, reportPath)
	if err != nil {
		return err
	}
	fmt.Println(url)
	return nil
}

// doPost is the core of the post operation, shared by the CLI and the MCP
// server. It returns the posted comment's URL.
func doPost(mrArg, reportPath string) (string, error) {
	host, iid, err := parseMRArg(mrArg, envHost())
	if err != nil {
		return "", err
	}
	body, err := os.ReadFile(reportPath)
	if err != nil {
		return "", fmt.Errorf("cannot read report file: %w", err)
	}
	text := string(body)
	if strings.TrimSpace(text) == "" {
		return "", errors.New("report file is empty - refusing to post an empty comment")
	}

	client, err := newGitLabClient(host)
	if err != nil {
		return "", err
	}
	posted, _, err := client.Notes.CreateMergeRequestNote(project, iid,
		&gitlab.CreateMergeRequestNoteOptions{Body: &text})
	if err != nil {
		return "", fmt.Errorf("posting comment failed: %w", classifyErr(host, err))
	}
	slog.Info("Report posted to merge request", "mr_iid", iid)
	return fmt.Sprintf("https://%s/%s/-/merge_requests/%d#note_%d", host, project, iid, posted.ID), nil
}

// newGitLabClient builds an SDK client for one host, authenticated by the
// user's own GITLAB_TOKEN. TLS is always verified - there is deliberately
// no skip option.
func newGitLabClient(host string) (*gitlab.Client, error) {
	token := os.Getenv("GITLAB_TOKEN")
	if token == "" {
		return nil, fmt.Errorf("GITLAB_TOKEN is not set - create a personal access token (api scope) on https://%s and export it as GITLAB_TOKEN", host)
	}
	// The default transport verifies TLS against the OS trust store.
	return gitlab.NewClient(token,
		gitlab.WithBaseURL("https://"+host),
		gitlab.WithHTTPClient(&http.Client{Timeout: 60 * time.Second}))
}

// parseMRArg accepts a bare IID or a full MR URL; returns (host, iid).
func parseMRArg(arg, defaultHost string) (string, int64, error) {
	if m := mrURLRe.FindStringSubmatch(arg); m != nil {
		if m[2] != project {
			return "", 0, fmt.Errorf("expected an MR of %s, got %s", project, m[2])
		}
		iid, err := strconv.ParseInt(m[3], 10, 64)
		if err != nil {
			return "", 0, fmt.Errorf("invalid MR IID %q", m[3])
		}
		return strings.ToLower(m[1]), iid, nil
	}
	if iid, err := strconv.ParseInt(arg, 10, 64); err == nil && iid > 0 {
		return defaultHost, iid, nil
	}
	return "", 0, fmt.Errorf("expected an MR IID or MR URL, got %q", arg)
}

// fetchNotes lists all MR notes, newest first, with pagination.
func fetchNotes(client *gitlab.Client, host string, iid int64) ([]note, error) {
	orderBy, sortDir := "created_at", "desc"
	opts := &gitlab.ListMergeRequestNotesOptions{
		// PerPage 100 is the API maximum - fewest round trips.
		ListOptions: gitlab.ListOptions{PerPage: 100},
		OrderBy:     &orderBy,
		Sort:        &sortDir,
	}
	var notes []note
	for {
		page, resp, err := client.Notes.ListMergeRequestNotes(project, iid, opts)
		if err != nil {
			return nil, classifyErr(host, err)
		}
		for _, n := range page {
			notes = append(notes, fromSDK(n))
		}
		if resp.NextPage == 0 {
			return notes, nil
		}
		opts.Page = resp.NextPage
	}
}

func fromSDK(n *gitlab.Note) note {
	var out note
	out.ID = int64(n.ID)
	out.Body = n.Body
	out.Author.Username = n.Author.Username
	if n.CreatedAt != nil {
		out.CreatedAt = n.CreatedAt.UTC().Format(time.RFC3339)
	}
	return out
}

// classifyErr distinguishes the failure modes the skill relays to the
// user: VPN down, bad token, missing CA, and missing MR.
func classifyErr(host string, err error) error {
	msg := err.Error()
	switch {
	case strings.Contains(msg, "no such host"), strings.Contains(msg, "dial tcp"),
		strings.Contains(msg, "i/o timeout"), strings.Contains(msg, "connection refused"):
		return fmt.Errorf("cannot reach %s - are you on the VPN? (%v)", host, err)
	case strings.Contains(msg, "certificate"), strings.Contains(msg, "x509"):
		return fmt.Errorf("TLS verification for %s failed - install its CA in the system trust store (%v)", host, err)
	case strings.Contains(msg, "401"), strings.Contains(msg, "403"):
		return fmt.Errorf("authentication to %s failed - check that GITLAB_TOKEN is valid and has the api scope (%v)", host, err)
	case strings.Contains(msg, "404"):
		return fmt.Errorf("merge request not found on %s/%s (%v)", host, project, err)
	}
	return err
}

// extractDiffURLs returns the URLs from the newest devtools-bot Diffs
// comment (notes arrive newest first).
func extractDiffURLs(notes []note) ([]string, error) {
	for _, n := range notes {
		if n.Author.Username != botUsername || !strings.HasPrefix(n.Body, diffsMarker) {
			continue
		}
		var urls []string
		for _, m := range urlRe.FindAllStringSubmatch(n.Body, -1) {
			urls = append(urls, m[1])
		}
		if len(urls) > 0 {
			slog.Debug("Found devtools-bot diff URLs", "count", len(urls))
			return urls, nil
		}
	}
	return nil, fmt.Errorf("no %q comment from %s found on this MR - either it is not a deployment MR, or the bot has not commented yet",
		diffsMarker, botUsername)
}

// extractGuidance collects /soundings note comments, oldest first.
func extractGuidance(notes []note, mrURL string) []guidanceEntry {
	guidance := []guidanceEntry{}
	for _, n := range notes {
		m := guidanceRe.FindStringSubmatch(n.Body)
		if m == nil {
			continue
		}
		if n.CreatedAt == "" {
			slog.Warn("Skipping guidance with empty CreatedAt", "note_id", n.ID)
			continue
		}
		slog.Debug("Found app-interface user guidance", "author", n.Author.Username)
		guidance = append(guidance, guidanceEntry{
			Content:    m[1],
			Author:     n.Author.Username,
			Date:       n.CreatedAt,
			CommentURL: fmt.Sprintf("%s#note_%d", mrURL, n.ID),
		})
	}
	// Notes arrive newest first; the report reads best oldest first.
	for i, j := 0, len(guidance)-1; i < j; i, j = i+1, j-1 {
		guidance[i], guidance[j] = guidance[j], guidance[i]
	}
	return guidance
}

func envHost() string {
	if h := os.Getenv("APP_INTERFACE_HOST"); h != "" {
		return h
	}
	return defaultHost
}

func envThreshold(name string) (*int, error) {
	v := os.Getenv(name)
	if v == "" {
		return nil, nil
	}
	n, err := strconv.Atoi(v)
	if err != nil || n < 0 || n > 100 {
		return nil, fmt.Errorf("%s must be an integer between 0 and 100, got %q", name, v)
	}
	return &n, nil
}

// validateThresholdOrder catches a misconfigured pair of threshold env vars
// (e.g. accidentally swapped) at resolve time, rather than letting it
// surface later as a confusing failure deep inside soundings' own render
// step. A nil threshold - meaning its env var wasn't set - never triggers
// this: soundings' own defaults apply in that case, and there's nothing to
// compare.
func validateThresholdOrder(autoDeploy, reviewRequired *int) error {
	if autoDeploy == nil || reviewRequired == nil {
		return nil
	}
	if *autoDeploy < *reviewRequired {
		return fmt.Errorf("SOUNDINGS_AUTO_DEPLOY_THRESHOLD (%d) must be >= SOUNDINGS_REVIEW_REQUIRED_THRESHOLD (%d)",
			*autoDeploy, *reviewRequired)
	}
	return nil
}
